config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#home'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :origin, :presence => true

  scope :recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}
  scope :usa, -> { where(origin: "United States") }

  COUNTRY_LIST = [
    "United States of America",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas, The",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cabo Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of the",
    "Congo, Republic of the",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia, The",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territories",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ]

  before_save(:titleize_product)

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, :presence => true
  validates :content_body, {:presence => true, :length => { :minimum => 50, :maximum => 250 }}
  validates :rating, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

        
  validate :password_complexity
  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[a-z])(?=.*?[0-9]).{6,20}$/

    errors.add :password, 'Complexity requirement not met. Length should be 6-20 characters and include: 1 lowercase and 1 digit'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :only => [:new, :edit, :create, :update, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
      @products = Product.all.paginate(page: params[:page], per_page: 10)
      render :index
  end

  def home
    @products = Product.all
    if params[:sort] == "recent"
      @products = Product.recent
    elsif params[:sort] == "most_reviews"
      @products = Product.most_reviews
    else params[:sort] == "usa"
      @products = Product.usa
      render :home
    end
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      flash[:notice] = "Your product was not added."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:notice] = "Your product was not updated."
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new]
  before_action :only => [:edit, :update, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  
  def show
    @review = Review.find(params[:id])
    @product = @review.product
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@review.product)
    else
      flash[:notice] = "Your product was not added."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_review_path(@product, @review)
    else
      flash[:notice] = "Your product was not added."
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) %></title>
    <link rel="icon" href="https://iconarchive.com/download/i27128/ph03nyx/super-mario/Paper-Mario.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= flash[:alert] %>
            <%= flash[:notice] %>
            <h1>Mario's Specialty Food Products</h1>
            <ul>
              <% if user_signed_in? %>
                <b><div>Signed in as: <%= current_user.email.split('@')[0].capitalize %></div></b>
              <% end %>
              <% if current_user %>
                <h6><%= link_to "Edit Account", edit_user_registration_path %></h6>
                <h6><%= link_to 'Logout', destroy_user_session_path, method: :delete %></h6>
              <% else %>
                <h6><%= link_to "Sign-In", new_user_session_path%></h6>
                <h6><%= link_to "Sign-Up", new_user_registration_path%></h6>
              <% end %>
              <h6><%= link_to "Home", root_path %></h6>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <hr>

    <div class="container">
      <%= yield %>
    </div>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <div class="icon-bar">
      <a href="http://www.facebook.com" class="facebook"><i class="fa fa-facebook"></i></a>
      <a href="http://www.twitter.com" class="twitter"><i class="fa fa-twitter"></i></a>
      <a href="http://www.google.com" class="google"><i class="fa fa-google"></i></a>
      <a href="http://www.linkedin.com" class="linkedin"><i class="fa fa-linkedin"></i></a>
      <a href="http://www.youtube.com" class="youtube"><i class="fa fa-youtube"></i></a>
    </div>

  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for [ @product ] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :origin %>
  <%= f.select(:origin, Product::COUNTRY_LIST) %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<% content_for(:title, "Mario's | Edit Product") %>

<h1>Edit Product</h1>
<br>
<%= render "form" %>

app/views/products/home.html.erb
<% content_for(:title, "Mario's Foods") %>

<div class="about">
  <h3>|About Mario's Foods|</h3>
    <p>Mario's has been offering consumers with high-quality food at reasonable pricing since 2000. We place a high value on customer happiness. That is why we have made it simple to write a product review and have posted all of them on our website. Share your experience.</p><br><br><hr>

  <div class="wrapper">
    <a href="?sort=recent"><button class="btn btn-default">Recently added</button></a>
    <a href="?sort=most_reviews"><button class="btn btn-default">Most Reviews</button></a>
    <a href="?sort=usa"><button class="btn btn-default">Made in USA</button></a>
    <button class="btn btn-default"><%= link_to "All Products", products_path %></button>
  </div>

  <hr>
  <br>
  <h1>Products</h1>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
</div>
<hr>

<div class="row">
  <div class="column">
    <%= image_tag "banana.jpeg" %>
    <%= image_tag "baskets.jpeg" %>
    <%= image_tag "blueberries.jpeg" %>
    <%= image_tag "bokchoy.jpeg" %>
    <%= image_tag "cucumber.jpeg" %>
  </div>
  <div class="column">
    <%= image_tag "fish.jpeg" %>
    <%= image_tag "greenOnions.jpeg" %>
    <%= image_tag "onions.jpeg" %>
    <%= image_tag "potatoes.jpeg" %>
    <%= image_tag "produce.jpeg" %>
    <%= image_tag "shopping.jpeg" %>
    <%= image_tag "mario-luigi-yoschi.jpg" %>
  </div>
  <div class="column">
    <%= image_tag "strawberries.jpeg" %>
    <%= image_tag "shopping1.jpeg" %>
    <%= image_tag "tomatoes.jpeg" %>
    <%= image_tag "asparagus.jpeg" %>
    <%= image_tag "customers.jpeg" %>
    <%= image_tag "mix.jpeg" %>
    <%= image_tag "peaches.jpeg" %>
    <%= image_tag "eggs.jpeg" %>
  </div>
  <div class="column">
    <%= image_tag "peppers.jpeg" %>
    <%= image_tag "pineapple.jpeg" %>
    <%= image_tag "radish.jpeg" %>
    <%= image_tag "carrots.jpeg" %>
    <%= image_tag "lemons.jpeg" %>
  </div>
</div>
<hr>
<footer>
  <div class="headerImage">
    <h4>Contact Info: | t: 123.456.7890 | e: marioandluigi@goodfoods.com</h4>
  </div>
</footer>

app/views/products/index.html.erb
<% content_for(:title, "Mario's Foods") %>


<div class="about">
  <h3>|About Mario's Foods|</h3>
    <p>Mario's has been offering consumers with high-quality food at reasonable pricing since 2000. We place a high value on customer happiness. That is why we have made it simple to write a product review and have posted all of them on our website. Share your experience.</p><br><br><hr>

  <div class="wrapper">
    <button class="btn btn-default"><%= link_to "Home", root_path %></button>
    <% if current_user && current_user.admin %>
    <button class="btn btn-default"><%= link_to "New Product", new_product_path %></button>
    <% end %>
  </div>

  <hr>
  <br>
  <h1>Products</h1>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
  <%= will_paginate @products %>
</div>

app/views/products/new.html.erb
<% content_for(:title, "Mario's | New Product") %>

<h1>Add a New Product</h1>
<br>
<%= render "form" %>

app/views/products/show.html.erb
<% content_for(:title, "Mario's | Product") %>

<div class="cancel">
  <h1>Product: <%= @product.name %></h1>
  <div class="cost">
  <h3>Cost: $<%= @product.cost %></h3>
  </div><br><br>
  <h3>Origin: <%= @product.origin %></h3>
</div><br><br><br><br><br><br><br><br><br>

<ul>
  <% if @reviews.any? %>
    <% @reviews.each do |review| %>
      <li>Reviewed by: <%= link_to review.author, product_review_path(@product, review) %></li>
    <% end %>
    <% else %>
      <h2>There are no reviews for this product.</h2>
    <% end %>
</ul><br><br>

  <% if current_user && current_user.admin %>
  <div class="wrapper">
    <button class="btn btn-success"><%= link_to "Edit Product", edit_product_path(@product) %></button>
    <button class="btn btn-success"><%= link_to "Delete Product", product_path(@product),
                  :data => {:confirm => "Are you sure?",
                  :method => "delete"} %></button>
    <% end %>
    <% if user_signed_in? %>
      <button class="btn btn-success"><%= link_to "Write a Review", new_product_review_path(@product.id) %></button>
    <% end %>
  </div>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating, min: 1, max: 5  %>

  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<% content_for(:title, "Mario's | Edit Review") %>

<h1>Edit Review</h1>
<br>
<%= render "form" %>

app/views/reviews/new.html.erb
<% content_for(:title, "Mario's | New Review") %>

<div class="about">
<h1>Write a Review for <%= @product.name %></h1>
</div>
<br>
<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for(:title, "Mario's | Reviews") %>

<div class="about">
  <h1>Author: <%= @review.author %></h1>
  <h1>Review: <%= @review.content_body %></h1>
  <h1>Rating: <%= @review.rating %></h1>
</div>

  <% if current_user && current_user.admin %>
    <%= link_to "Edit Review", edit_product_review_path(@product, @review) %> |
    <%= link_to "Delete Review", product_review_path(@review),
                      :data => {:confirm => "Are you sure?",
                      :method => "delete"} %>
  <% end %>